# Generated by Django 5.1.3 on 2024-12-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/%u/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='preview',
            field=models.FileField(blank=True, null=True, upload_to='previews/'),
        ),
    ]
